const actionTypes = {
  LOAD_CRYPTO_COIN_LIST: "LOAD_CRYPTO_COIN_LIST",
  LOAD_CRYPTO_MARKETS_LIST: "LOAD_CRYPTO_MARKETS_LIST",
  LOAD_CRYPTO_COIN_BY_ID: "LOAD_CRYPTO_COIN_BY_ID",
  UPDATE_CRYPTO_COIN_BY_ID: "UPDATE_CRYPTO_COIN_BY_ID",
};

export default actionTypes;
