const actionTypes = {
  LOAD_CRYPTO_COIN_LIST: "LOAD_CRYPTO_COIN_LIST",
  LOAD_CRYPTO_COIN_BY_ID: "LOAD_CRYPTO_COIN_BY_ID",
  LOAD_DERIVATIVES_LIST: "LOAD_DERIVATIVES_LIST",
  CHANGE_LIST: "CHANGE_LIST",
  ERROR_NO_SAVEDCURRENCY: "ERROR_NO_SAVEDCURRENCY",
};

export default actionTypes;
